*This tutorial is written by me it is to be used as is. most of the notes highlight differences or special syntax I learned in Julia. I already have knowledge of C++,MATLAB and Python. I will skip the commonalities like simple operators and all that*

# 1. Basics and notes


The difference between `print` and `println` is that the latter adds a new line at the end

In [68]:
a = [ "1  " "  2  "]
for i in a 
    print(i)
end
for i in a 
    println(i)
end

1    2  1  
  2  


Julia uses `^` for exponentiation unlike python's`**`

rational numbers are represented as `<Numerator>//<Denominator>` in the simplist form

In [70]:
(3*4*5)//(6*4*5)

1//2

You can write unicode characters in Julia. To use some of the characters use the \ (backslash) and start writing and press tab to search and enter to select and another tab to convert to the unicode characters
Check [here](https://docs.julialang.org/en/v1/manual/unicode-input/index.html) for the available shortcuts

In [73]:
α = β = 5

5

In [75]:
📵 = true

true

    By convention, a function name ending with a ! indicates that it will mutate or destroy the value of one or more of its arguments.

## Julia Types

To get a type of a Julia variable you can use the `typeof()` function

In [88]:
x=5
typeof(x)

Int64

Julia types are in a form of a tree. Like in the following:
![Number types](https://upload.wikimedia.org/wikipedia/commons/4/40/Type-hierarchy-for-julia-numbers.png) 
for more info click [here](https://en.wikibooks.org/wiki/Introducing_Julia/Types) 
One important concept in the above link is abtract and concrete types

In [92]:
Array{Int64, 2}(undef,1,2)

1×2 Array{Int64,2}:
 139962362432320  139962362432320

## Arrays

To initialize an unitialized array with dimension (x, y, z ...) we use the following syntax:
```Julia
Array{T}(undef/missing/nothing, x, y, z, ... )
## Or also we can specify the number of dims after T like that:  However the the dimensions passed should be n
Array{T n}(undef x, y, z, ...(n elements))
# This is already done automatically
```
`Array{T,N}` by itself is a DataType  
Array indexing is 1 based like MATLAB. 
Also there exists initializers for `ones(T,dims...)`, `zeros(T,dims...)`, `trues(dims...)`, `falses(dims...)`

In [109]:
x  = Array{String,3}(undef,1 , 2 , 3)

1×2×3 Array{String,3}:
[:, :, 1] =
 #undef  #undef

[:, :, 2] =
 #undef  #undef

[:, :, 3] =
 #undef  #undef

`eltype(A)` returns type of elements in array

In [110]:
eltype(x)

String

You can also write down arrays in this form:
Space make horizontal concatentaion with semicolons make vertical ones

In [124]:
y = [ [1 3]; [3 4 ] ]

2×2 Array{Int64,2}:
 1  3
 3  4

You can specify their types bywriting it before the the square bracket

In [135]:
y = Number[ Float64[1 3]; Int8[3 4 ] ]

2×2 Array{Number,2}:
 1.0  3.0
 3    4  

You can also create Arrays using Comprehsions i.e. using loops:

In [136]:
x = rand(8)
[ 0.25*x[i-1] + 0.5*x[i] + 0.25*x[i+1] for i=2:length(x)-1 ]

6-element Array{Float64,1}:
 0.6394121332080714
 0.557890188526398 
 0.4956045440488581
 0.6346812139604789
 0.6306878077559185
 0.6796086805190537

The recommended ways to iterate over a whole array are

```Julia
for a in A
    # Do something with the element a
end

for i in eachindex(A)
    # Do something with i and/or A[i]
end
```

For more info check the documentation [here](https://docs.julialang.org/en/v1/manual/arrays)

# 2. IO

Reading a file involves the Open function which is a general function used for Inputs and outputs.
```Julia
open(<"File Path string"> , <"Here we use either boolean for the modes of Mode strings">) 
```
Check [here](https://docs.julialang.org/en/v1/base/io-network/index.html) for more details on the modes.
To read a file directly we can use the function read. 
we can pass to the first argumant a string of the path or an IO object(like the output of open).
If you pass the second argument as String the whole file is read as abstract string. if using another type to read it will read a character by character like a buffer.


In [2]:
test_a = ["I " "am"  "Just" "testing" "Inputs" "Outputs"] 

2×3 Array{String,2}:
 "I "       "am"      "Just"   
 "testing"  "Inputs"  "Outputs"

To write an array in a file you can use Delimited Files to do it. Here you can send an Array and a delimitting character to place after each element in the array as following.
The safe way to autmatically exit a file after it's opened use the following syntax
```Julia
open(...) do <variableName>
    #Do something 
end
``` 
An example is shown next 

In [13]:
using DelimitedFiles
open("Texting.txt" , "w") do file
    writedlm(file, test_a ,'\n')
end

Here I will test reading the file as a string using read delimited `readdlm`:


In [15]:
open("Texting.txt" , "r") do file
    readdlm(file ,'\n')
end

6×1 Array{Any,2}:
 "I "     
 "am"     
 "Just"   
 "testing"
 "Inputs" 
 "Outputs"

Also equivilent to read delimited on '\n' ( new line character ) is the readlines function


In [17]:
readlines("Texting.txt")

6-element Array{String,1}:
 "I "     
 "am"     
 "Just"   
 "testing"
 "Inputs" 
 "Outputs"

Next we try the read function and passing `String` as the second argument:

In [29]:
read("Texting.txt",String)

"I \nam\nJust\ntesting\nInputs\nOutputs\n"

If we used char instead of string it reads characted by character. eof fhunction checks if the end of file is reached.

In [66]:
open("Texting.txt","r") do file
    while(!eof(file))
        println(read(file,Char))
    end
end

I
 


a
m


J
u
s
t


t
e
s
t
i
n
g


I
n
p
u
t
s


O
u
t
p
u
t
s




if we use `readline` it will get each line

In [62]:
open("Texting.txt","r") do file
    for i in 1:6
        println(readline(file))
    end
end

I 
am
Just
testing
Inputs
Outputs


Also you can iterate over lines using `eachline`

In [63]:
open("Texting.txt","r") do file
    for i in eachline(file)
        println(i)
    end
end

I 
am
Just
testing
Inputs
Outputs
